hngi/Gateapp-api

- README.md
> Added instructions for starting the project and sending PRs

- app/Http/Controllers/UserProfileController.php
Added codes to edit user profile in the update method.
> Added profile update feature

- app/Http/Controllers/UserProfileController.php
Made the data email receives unique.
> Corrected some validation errors

- app/Http/Controllers/VisitorController.php
- routes/v1.php
route for get all visitor and single visitor
> visitor route

- app/Http/Controllers/VisitorController.php
- routes/v1.php
#Endpoint 05.  Bootstrap [ PUT api/visitor/{id} ] and Bootstrap [ DELETE api/visitor/{id} ]
> Visitor api andy

- app/Http/Controllers/EstateController.php
- routes/v1.php
Creating Estates and Editing Estate Information
> Estate Push &  Put requests

- README.md
- app/Http/Controllers/UserProfileController.php
added api routes for users to README file and made some comments easing understanding and reference to UserProfileController
> Added to the associative route listing in README

- app/Http/Controllers/ServiceProviderController.php
Added Validation to require all field input
> Updated serviceprovidercontroller.php

- app/Http/Controllers/GatemanController.php
- routes/v1.php
Login as authorized gateman user
Do an Put request on  /gateman/response
Passing in the 
1.) resident_gateman id(invitation_id)
2.) Accept(1) or decline(0)(request_status)
Example
{
"invitation_id" : 1, 
"request_status"  : 1
}
> Accept/Decline Resident Invitation

- app/Http/Controllers/SmsOtp.php
Added a controller for sending sms otp.
> Added a controller for sending sms otp

- app/Http/Controllers/ResidentController.php
- routes/v1.php
Resident to view his/her pending and accepted gateman invitation
> Resident to view his/her pending and accepted gateman invitation

- app/Http/Controllers/SmsOtp.php
> Added an exception handler

- app/Http/Controllers/ResidentController.php
- routes/v1.php
Endpoint for a resident to view his/her pending or accepted gateman invitation updated
> Endpoint for a resident to view his/her pending or accepted gateman invitation updated

- app/Http/Controllers/SmsOtp.php
Added a way to automatically get user phone number from database so that user phone number does not have to be passed as an argument.
> Added a way to automatically get user phone number from database

- app/Http/Controllers/SmsOtpController.php
I only removed the $ sign in from the $msg variable, so that users don't get an sms with the $ sign.
> Removed a mistake that could cause errors

- partners.html
- styles/navbar.css
> added little style to make the nav-bar alignment better on responsiveness

- .env
- app/Http/Controllers/SupportController.php
- app/Mail/SupportMail.php
- app/Support.php
- database/migrations/2019_10_23_145830_create_supports_table.php
- resources/views/email/support.blade.php
- routes/v1.php
This is the endpoint to enable users send support mails. Find attached images and updated documentation
[Documentation](https://documenter.getpostman.com/view/3775496/SVzw3fmR?version=latest)
> Can send support mails

- app/Http/Controllers/EstateAdmin/RegistrationController.php
- app/Http/Controllers/EstateController.php
- app/Http/Controllers/ServiceProviderController.php
- app/Http/Controllers/Statistics/EstateStatsController.php
- app/Http/Controllers/Statistics/ServiceStatsController.php
- app/Http/Controllers/Statistics/UserStatsController.php
- app/Http/Controllers/Statistics/VisitorStatsController.php
- app/Http/Middleware/VerifyEstateAdminMiddleware.php
- app/Service_Provider.php
- routes/v1.php
See My Documentation here 
[https://documenter.getpostman.com/view/9048286/SW11VxZN?version=latest](url)
> Added Routes for SuperAdmin to see Stats Data on the backend 

- app/Estate.php
- app/Http/Controllers/EstateController.php
- routes/v1.php
[https://documenter.getpostman.com/view/9048286/SW11Wdbk?version=latest](Documentation)
> Updated the add and update Estate routes to allow image upload

- app/Http/Controllers/ServiceProviderController.php
I added a search method which is my second task, this method provides the ability to get service provider deatils. e.g name, phone etc based on the provided id.
> Added search method and corrected some bugs

- app/Http/Controllers/GatemanController.php
- app/Http/Controllers/VisitorController.php
- app/Visitor.php
- app/Visitor_History.php
- database/migrations/2019_10_09_002748_create_visitors_table.php
- database/migrations/2019_10_30_113945_create_visitors_history_table.php
- routes/v1.php
[https://documenter.getpostman.com/view/9048286/SW11Xe3Z?version=latest](url)
> Update Checkout route, and create a history table to keep visitor visits

- app/Http/Controllers/ServiceProviderController.php
- routes/v1.php
Api endpoint to create service provider request
> Api endpoint to create service provider request

- app/Http/Controllers/GatemanController.php
- app/Http/Controllers/VisitorController.php
- routes/v1.php
> Added estate-admin gateman management

- app/Http/Controllers/ServiceProviderController.php
> Search method API now works perfectly

- app/Http/Controllers/ServiceProviderController.php
- routes/v1.php
Tweaked Existing Service Providers API to display corresponding Estates and Category instead of just Also added a count function easy count on how many service providers are listed.
Service Provided grouped by Estate
> Tweaked Existing Service Providers API 

- app/Http/Controllers/ServiceProviderController.php
> Service provider search, suspend, unsuspend, delete feature now works

- app/Http/Controllers/VisitorController.php
- app/Visitor.php
- database/migrations/2019_10_30_182618_add_banned_to_visitors_table.php
- routes/v1.php
-view banned visitors
- view banned visitors by estate
- remove visitor's from ban
> Visitor banning

- aboutus.html
- styles/seunogunyemi.css
@cemma2035 please merge. Thanks
> added the about us page

- styles/termsandconditions.css
- termsandconditions.html
> built the terms and conditions page

- js/apis/residents/allResidentStats.js
- js/apis/residents/getAllResidents.js
- js/apis/visitors/allVisitors.js
> fixed authorization

- js/general/gateman.js
- super-admin/gateman-tab.html
> updated fetchGateman info to show modal details

- app/Http/Controllers/UserProfileController.php
- routes/v1.php
/api/v1/user/edit/12   to edit user base on id
/api/v1/user/edit/       original still okay, to edit authenticated user
/api/v1/user/delete/12   to delete user base on id
/api/v1/user/delete/       original still okay, to delete authenticated user
> edit user and delete user by ID, modified routes

- app/Http/Controllers/UserProfileController.php
- routes/v1.php
> Revert "edit user and delete user by ID, modified routes"

- estate-admin/dashboard-residents.html
- styles/estate-dashboard-sidebar.css
I added on the residents page table:
> Worked on the residents page

- estate-admin/dashboard-initial.html
- estate-admin/dashboard-residents.html
- estate-admin/layout/header.js
- estate-admin/layout/sidebar.js
- js/apis/estateAdmin/estate-guards.js
- styles/estate-dashboard-sidebar.css
I fixed the alignments on the dashboard-initial page and other minor things:
> Fixed alignments and other minor things

- estate-admin/dashboard-initial.html
- estate-admin/layout/header.js
- styles/estate-dashboard-sidebar.css
I improved the header's responsiveness and also the alignments...
> Improved the header's responsiveness
